[build]
  command = "npm run build"
  publish = "dist"

# Define build plugin to optimize images during build
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Set cache control headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Define redirects if needed
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 